// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPg8DSHYmr9bSuUiAVOijc_tE3d56BC0I',
    appId: '1:468464607433:web:d3ec182049f62ea9416d18',
    messagingSenderId: '468464607433',
    projectId: 'flutterflexmen',
    authDomain: 'flutterflexmen.firebaseapp.com',
    storageBucket: 'flutterflexmen.appspot.com',
    measurementId: 'G-RZQ47XVLLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsg90RlmRdn8voj0b5EHDbORiXY7EefW4',
    appId: '1:468464607433:android:64aa70506c7506e4416d18',
    messagingSenderId: '468464607433',
    projectId: 'flutterflexmen',
    storageBucket: 'flutterflexmen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-uOZ3KjDC6OgP7wyi8mtjuQ7U3Y8yDA',
    appId: '1:468464607433:ios:ab9bbce3ae110498416d18',
    messagingSenderId: '468464607433',
    projectId: 'flutterflexmen',
    storageBucket: 'flutterflexmen.appspot.com',
    iosBundleId: 'com.example.flexmenflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-uOZ3KjDC6OgP7wyi8mtjuQ7U3Y8yDA',
    appId: '1:468464607433:ios:ab9bbce3ae110498416d18',
    messagingSenderId: '468464607433',
    projectId: 'flutterflexmen',
    storageBucket: 'flutterflexmen.appspot.com',
    iosBundleId: 'com.example.flexmenflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPg8DSHYmr9bSuUiAVOijc_tE3d56BC0I',
    appId: '1:468464607433:web:267c4667dc6b8652416d18',
    messagingSenderId: '468464607433',
    projectId: 'flutterflexmen',
    authDomain: 'flutterflexmen.firebaseapp.com',
    storageBucket: 'flutterflexmen.appspot.com',
    measurementId: 'G-QGY0ZWEP31',
  );
}
